### ISSUE TITLE
Copy to clipboard notification

### ISSUE THREAD

**Issue by vini23hot** [quickcep/frontend#3]
We need to **notify that the text has been copied to clipboard** when user clicks on _Endpoint_ input.

**Comment by kirtansakariya** [comment]
Do you mind if I take this one?
I was just thinking of adding some sort of alert when the first function in `/js/main.js` is triggered. Is that what you were looking for?

**Comment by kirtansakariya** [comment]
I implemented a solution on a new branch. It's not letting me push for some reason. It's telling me permission denied when I try to push and create a new branch for my issue.

**Comment by vini23hot** [comment]
@kirtansakariya Did you fork the repository, create a new remote branch, clone it and try to push to this new branch?

**Comment by kirtansakariya** [comment]
I believe it was addressed in the pull request by RuanAragao. So I'll drop this one. Thanks for the help though @vini23hot
